### ISSUE TITLE
Rationale for not using NS+secret resources

### ISSUE THREAD

**Issue by AntonOfTheWoods** [oscar6echo/fief-k3d-deploy#4]
I am completely new to `kustomize` (I have been using `helm` for several years), so am not clear on a couple of design choices. Both the namespace and secrets could have been included as resources, rather than created separately. with commands Both can also easily be customised with overlays after. Is there some reason, or is it just a matter of personal preference to do it this way? I added both in my overlay for a preprod server (on a remote cloud server) and it seems to work fine. Is there something to be aware of?

**Comment by oscar6echo** [comment]
Kustomize can be used to create ns and secrets too.  
I updated the README with both options.  

I tend to separate kube assets - to undo or update separately (`k apply -k .` or `k delete -k .` ):
+ ns - created only once
+ secrets - can change, also frequently extracted from vault in real deploy
+ persistent assets: pv and pvc, equivalent to disk and disk claims.
+ ephemeral ie. stateless - deploy must be updated if secrets are extracted from vault
